<?php

namespace Count\FanficBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BlockRoot
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRoot extends DocumentRepository
{
}