<?php

namespace Count\FanficBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * BlockChapter
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockChapter extends DocumentRepository
{
}