<?php

namespace Count\FanficBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * Block
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Block extends DocumentRepository
{
}