Count\FanficBundle\Document\BlockChapter:
    type: document
    repositoryClass: Count\FanficBundle\Repository\BlockChapter
    collection: blocksChapter
    fields:
    referenceOne:
        title:
            targetDocument: Count\FanficBundle\Document\BlockTitle