Count\FanficBundle\Document\BlockTitle:
    type: document
    repositoryClass: Count\FanficBundle\Repository\BlockTitle
    collection: blocksTitle
    fields:
        content:
            type: string