Count\FanficBundle\Document\Metadata:
    type: embeddedDocument
    fields:
        id:
            id:  true
        name:
            type: string
        slug:
            type: string
            gedmo:
                slug:
                  unique: false
                  fields:
                    - name
        value:
            type: string
    indexes:
        index:
            keys:
                - slug
            order: asc